### ISSUE TITLE
font/truetype is not a valid mime type

### ISSUE THREAD

**Issue by Nettsentrisk** [jaicab/localFont#7]
The current correct IANA mime type for ttf fonts is application/font-sfnt; the new proposal from W3C is font/ttf or font/sfnt (either apply to ttf).

I'm not aware that "font/truetype" is registered anywhere as a mime type.

**Comment by jaicab** [comment]
I've been doing some research on this and seems like ttf doesn't have a MIME type per se. I had seen font/truetype in some places like FontSquirrel so that's why I went with that. 
But seems like the standard (what everybody is using) is application/x-font-ttf, so that's what I'm going to change it to. You can always edit it so I think using the most common option is the best plan for this.
