### ISSUE TITLE
Add unminified font loader source to repo

### ISSUE THREAD

**Issue by daaain** [jaicab/localFont#9]
Right now the actual font loader is just an inline, minified bit in the HTML, but it would be great to have it as "full" code in the repo so people can look at it, understand it, adapt it, improve it, etc.

Love your great "micro library" by the way, thanks a lot for putting this all together!

**Comment by jaicab** [comment]
I've been told this before, so I think I'm going to do it, maybe even use ES6 templates instead of the minified string. But you can check the [unminified script](https://gist.github.com/hdragomir/8f00ce2581795fd7b1b7) right now as it is available in the credits since it's actually what Smashing Magazine is using. 

Glad you like it! :+1:

**Comment by daaain** [comment]
Ah great, thanks a lot for the pointer!

I had a look at the comments, there's a link to a slightly improved version at the bottom, which doesn't crash IE8 and doesn't store a 404 response as cached font: https://gist.github.com/iamdarrenhall/53b5eea54ac4bc25d0a6

**Comment by jaicab** [comment]
Interesting! Now it makes more sense to add the script to the repo. I'll update soon!

**Comment by jaicab** [comment]
As promised, the full script is now included in the repo as [launcher.html](https://github.com/jaicab/localFont/blob/gh-pages/launcher.html).
I will test the improved version that fixes the problems on IE8 as well as other suggestions made in other issues and add them altogether.

**Comment by daaain** [comment]
Brilliant, thank you so much Jaime!
